### ISSUE TITLE
Eclipse update link doesn't work

### ISSUE THREAD

**Issue by jules1983** [LorenzoBettini/javamm#106]
The link https://dl.bintray.com/lorenzobettini/javamm/updates/ shows an error message "502 Forbidden"

**Comment by LorenzoBettini** [comment]
Yes, bintray has been shutdown. I'll provide a new update site in the next few days.

**Comment by LorenzoBettini** [comment]
The new update site https://lorenzobettini.github.io/javamm-releases/ is now available.
Make sure you remove the previous one and use this new one
