### ISSUE TITLE
command line

### ISSUE THREAD

**Issue by Guray00** [LorenzoBettini/javamm#134]
Does exists a way to run a javamm file from command line without using eclipse? I would like to use only the "interpreter" (maybe without direct installation on system) to run scripts. Thanks in advance

[ITALIAN]
Buongiorno, esiste la possibilità di eseguire un sorgente javamm direttamente da linea di comando senza utilizzare eclipse o un qualsivoglia IDE esterno? Mi piacerebbe utilizzare unicamente "l'interprete" per eseguire il file e ottenere l'eseguibile correlato, magari utilizzando direttamente i binari/sorgenti forniti senza un'installazione diretta sul sistema. Grazie in anticipo.

**Comment by LorenzoBettini** [comment]
I think there's some misunderstanding here: Java-- does not provide an interpreter, it compiles Java-- programs into plain Java programs. In Eclipse, once the Java programs are generated they are automatically compiled into byte-code. In Eclipse when you use "Run As" on a Java-- program, under the hood, the generated Java program is executed.
Finally, Java-- is meant to be used in an IDE (Eclipse) as a teaching language.
Summarizing, it does not make much sense to compile and run Java-- programs from the command line.

Of course, it is possible to provide a Maven plugin to compile Java-- programs into Java programs, but then you'll have to configure Maven appropriately, which I don't think it's what you meant.

Or did you mean something else?

**Comment by Guray00** [comment]
I understand, thank you. I was searching a way to teach Java-- using other IDEs, like replit on the web.
