### ISSUE TITLE
Inizialization bug

### ISSUE THREAD

**Issue by tiezzi** [LorenzoBettini/javamm#31]
in Java-- seems that variables are always initialised by default, while this does not happen in Java. For example, let us consider the following code:
int x;
int y = x;

In Java it generates an error at compile-time, while in Java-- it doesn't. In fact, x and y are implicitly initialised to 0.

**Comment by LorenzoBettini** [comment]
Working on this on branch task_31-Inizialization_bug

**Comment by LorenzoBettini** [comment]
The Java compiler's error is of the shape

```
The local variable i may not have been initialized
```

**Comment by LorenzoBettini** [comment]
available now in the new release 1.3.2
