### ISSUE TITLE
Missing return

### ISSUE THREAD

**Issue by tiezzi** [LorenzoBettini/javamm#32]
In the following Java-- method (drawn from the Gocce di Java textbook):

int massimoDueNumeri( int n1, int n2 ) { int massimo = n1;
if (n1<n2) {
massimo = n2;
return massimo; }
}

the return statement could be not executed. To be compliant with Java, the Java-- compiler should raise an error "This method must return a result of type int".
This does not happen because in the translation Java-- to Java it is added a "return 0" statement.

**Comment by LorenzoBettini** [comment]
It will be available in the forthcoming 1.3.1

**Comment by LorenzoBettini** [comment]
Version 1.3.1 has been released, please update your installation :)
