### ISSUE TITLE
A doubt about global variables

### ISSUE THREAD

**Issue by tiezzi** [LorenzoBettini/javamm#33]
I have a doubt about global variables in Java--. I would expect that a variable declared outside methods would have a global scope in the Java-- program, instead its scope is the code corresponding to the main (indeed it is a local variable of the main method of the corresponding Java class, not a static field of the class). For example, the following Java-- code

void stampa(){
	System.out.print("Hello"+w);
}
String w = "World";
stampa();

uses w as a global variable, and indeed it does not compile. 

So, my doubt is: what is the motivation underlying the fact that Java-- does not provide global variables?

**Comment by LorenzoBettini** [comment]
Since global variables are considered bad programming style, we completely ruled them out from Java--. Statements outside any functions are the main block of the programs and, consistently with Java, variables inside a Java's main block are not global variables.
