### ISSUE TITLE
Wrong link in the README.md

### ISSUE THREAD

**Issue by MesSem** [LorenzoBettini/javamm#36]
Hi, 
the link in README.md file :"http://sourceforge.net/projects/javamm/files/updates/releases" not redirect in the folder where there is the plugin inside an zip archive.

The link direct in a point where isn't possible download all the library, only the .jar file. I think it's better insert this link: "http://sourceforge.net/projects/javamm/files/zips/1.3.0/".

**Comment by LorenzoBettini** [comment]
Hi
The url is correct: it is an Eclipse update site and it must be used as such, that is, to install plugins in an existing Eclipse, not to download jars or zips manually.  Then there is the link to download complete Eclipse distributions with Java-- already installed. The zips you mentioned are currently meant for internal use only, and indeed they are not documented.

**Comment by LorenzoBettini** [comment]
The installation instructions should be clearer now
