### ISSUE TITLE
Problem with self-assessment projects

### ISSUE THREAD

**Issue by piluc** [LorenzoBettini/javamm#41]
It seems to me that there is some bug in the automatic update of a self-assessment project. If I change the name of the student project (for instance, from Sveglia.student to, simply, Sveglia), when I successively change the teacher solution, the following error occurs during the building:

Errors occurred during the build.
Errors running builder 'Java-- SelfAssessment Project Builder' on project 'Sveglia.teacher'.
org.eclipse.core.internal.resources.Project cannot be cast to org.eclipse.core.resources.IFolder

As a consequence, the teacher class in the student project is not updated.

If I subsequently rename the student project with the original name (that is, Sveglia.student), then everything works fine again.

**Comment by LorenzoBettini** [comment]
Yes, the student project's name is computed starting from the teacher's project name, thus, changing any of the two projects breaks everything. At the moment, that's the only way to keep the two projects in sync, i.e., based on the projects' names, and I don't see easy solutions besides the current one.

Do you think it's better to give the two projects different suffixes?

**Comment by piluc** [comment]
Ok. I think that the suffixes you have chosen are OK.
