### ISSUE TITLE
Method overloading

### ISSUE THREAD

**Issue by piluc** [LorenzoBettini/javamm#50]
The following code generates a "duplicate definition" error.

int convert(int[] a) {
	return a[0]+a[1];
}

int[] convert(int m) {
	return new int[] {m/2, m/2};	
}

Does it mean that method overloading is not supported?

**Comment by LorenzoBettini** [comment]
Indeed, method overloading is currently not supported.
I'll implement it ASAP.

**Comment by LorenzoBettini** [comment]
Version 1.3.4 has just been released with this fix!
