### ISSUE TITLE
Loops with true condition

### ISSUE THREAD

**Issue by piluc** [LorenzoBettini/javamm#59]
The following code

int d = 1;
while (1 == 1) {
	d++;
	if (d == 3)
		break;
}
while (2 == 2) {
	break;
}

generates the following error (on the second loop)

Multiple markers at this line
- Unreachable expression.
- Constant condition is always true.

The code is correctly compiled in Java. The error disappears if you delete the first while loop.

**Comment by LorenzoBettini** [comment]
In Java, this gives the same problem (i.e., without the break)

```
		int d = 1;
		while (1 == 1) {
			d++;
			
		}
		while (2 == 2) {
			break;
		}
```

So the problem seems to be that we don't take the break inside the while as a possible exit condition, giving the further while a chance to be executed.

**Comment by LorenzoBettini** [comment]
As in Java, we should only consider break, since this is invalid in Java as well

```
int d = 1;
while (1 == 1) {
	d++;
	if (d == 3)
		continue;
}
while (2 == 2) {
	break;
}
```
