### ISSUE TITLE
Matrix implicit conversion does not work

### ISSUE THREAD

**Issue by piluc** [LorenzoBettini/javamm#83]
The following code

void f(double[][] s) {}
int[][] a = {{1, 0, 0, -1, 1, 0, 0, 0}, {1, 0, -1, -1, 0, 0, -1, 0}};
f(a);

generates the following error: Type mismatch: cannot convert from int[][] to double[][]

It should not, right?

**Comment by LorenzoBettini** [comment]
You actually get the same compiler error from Java:

```java
public class Hello {

	static void f(double[][] s) {}
	
	public static void main(String[] args) {
		int[][] a = {{1, 0, 0, -1, 1, 0, 0, 0}, {1, 0, -1, -1, 0, 0, -1, 0}};
		f(a); // <- ERROR
	}
}
```

```The method f(double[][]) in the type Hello is not applicable 
 for the arguments (int[][])```

So this is not a bug of Java--, luckily ;)
