### ISSUE TITLE
'===' operator

### ISSUE THREAD

**Issue by piluc** [LorenzoBettini/javamm#90]
When writing the following Boolean expression
x == null
the following warning is produced
"The operator '==' should be replaced by '===' when null is one of the arguments."
But if I try to use the '===' operator, I get a compilation error.

**Comment by LorenzoBettini** [comment]
The warning was recently introduced in Xbase where === is available (but of course it is not available in Java). The warning should be disabled in Java--

**Comment by LorenzoBettini** [comment]
Will be part of the new release 1.8.0
